# Generated by Django 4.2.13 on 2024-08-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('type', models.CharField(choices=[('Live', 'Live'), ('Demo', 'Demo'), ('Draft', 'Draft')], default='Draft', max_length=50)),
                ('category', models.CharField(choices=[('Web-Applications', 'Web-Applications'), ('E-commerce', 'E-commerce'), ('Portfolio', 'Portfolio'), ('News', 'News'), ('Educational', 'Educational'), ('Forums', 'Forums'), ('Streaming', 'Streaming'), ('Real-Estate', 'Real-Estate')], default='Web-Application', max_length=50)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=200)),
                ('technology', models.CharField(max_length=200)),
                ('link', models.URLField(default='#')),
                ('views', models.IntegerField()),
            ],
        ),
    ]
