# Generated by Django 5.2 on 2025-04-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_app', '0002_websitelist_delete_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphicDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(default='https://raw.githubusercontent.com/MadhabChandra/image2/main/')),
                ('position', models.IntegerField(blank=True, default='0', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='websitelist',
            name='image',
            field=models.URLField(default='https://raw.githubusercontent.com/MadhabChandra/image2/main/'),
        ),
    ]
