# Generated by Django 5.2 on 2025-04-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_app', '0003_graphicdesign_alter_websitelist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitelist',
            name='position',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
